version: '3'
services:
  zookeeper:
    image: 'arm64v8/zookeeper:3.8'
    networks:
      - seobetter_network
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_TLS_CLIENT_AUTH=none
      - ZOO_TLS_QUORUM_CLIENT_AUTH=none

  kafka:
    image: 'bitnami/kafka:3.4.0'
    networks:
      - seobetter_network
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=LC://kafka:29092,LX://kafka:9092, CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LC:PLAINTEXT,LX:PLAINTEXT, CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LC
      #- BITNAMI_DEBUG=yes
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    networks:
      - seobetter_network
    ports:
      - "8989:8080"
    restart: always
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  mysql:
    image: mysql
    networks:
      - seobetter_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=232323
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw@!
      - MYSQL_DATABASE=seo-better-pay

  membership-service:
    image: seo-better-pay-membership-service:0.0.1-SNAPSHOT
    networks:
      - seobetter_network
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/seo-better-pay?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=mysqlpw@!
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - LOGGING_TOPIC=seobetterpay.logging.out.stdout

  banking-service:
    image: seo-better-pay-banking-service:0.0.1-SNAPSHOT
    networks:
      - seobetter_network
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/seo-better-pay?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=mysqlpw@!
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - LOGGING_TOPIC=seobetterpay.logging.out.stdout
      - SERVICE_MEMBERSHIP_URL=http://membership-service:8080

  money-service:
    image: seo-better-pay-money-service:0.0.1-SNAPSHOT
    networks:
      - seobetter_network
    ports:
      - "8083:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/seo-better-pay?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=mysqlpw@!
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - LOGGING_TOPIC=seobetterpay.logging.out.stdout
      - TASK_TOPIC=seobetterpay.task.topic
      - TASK_RESULT_TOPIC=seobetterpay.task.result.topic
      - SERVICE_MEMBERSHIP_URL=http://membership-service:8080

  logging-service:
    image: seo-better-pay-logging-service:0.0.1-SNAPSHOT
    networks:
      - seobetter_network
    restart: always
    depends_on:
      - zookeeper
      - kafka
    environment:
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - LOGGING_TOPIC=seobetterpay.logging.out.stdout
      - TASK_RESULT_TOPIC=seobetterpay.task.result.topic

  task-service:
    image: seo-better-pay-task-service:0.0.1-SNAPSHOT
    networks:
      - seobetter_network
    restart: always
    depends_on:
      - zookeeper
      - kafka
    environment:
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - LOGGING_TOPIC=seobetterpay.logging.out.stdout
      - TASK_TOPIC=seobetterpay.task.topic
      - TASK_RESULT_TOPIC=seobetterpay.task.result.topic

networks:
  seobetter_network:
    driver: bridge

