logging:
  level:
    com.car.sns: trace
    org.springframework.web.servlet: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always

